=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/Esquemas del XML (XSD)/batallas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Batallas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Batalla" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="num_Turnos" type="xs:integer"/>
                            <xs:element name="num_Ayudantes" type="xs:integer"/>
                        </xs:sequence>
                        <xs:attribute name="Enemigo_ID" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:positiveInteger">
                                    <xs:minInclusive value="1"/>
                                </xs:restriction>
                            </xs:simpleType> 
                        </xs:attribute>
                        <xs:attribute name="Jugador_ID" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:positiveInteger">
                                    <xs:minInclusive value="1"/>
                                </xs:restriction>
                            </xs:simpleType> 
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/Tablas en XML/batallas.xml
<?xml version="1.0" encoding="UTF-8"?>
<Batallas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="batallas.xsd">
   <Batalla Enemigo_ID="59" Jugador_ID="1">
      <num_Turnos>3</num_Turnos>
      <num_Ayudantes>0</num_Ayudantes>
   </Batalla>
   <Batalla Enemigo_ID="12" Jugador_ID="2">
      <num_Turnos>2</num_Turnos>
      <num_Ayudantes>3</num_Ayudantes>
   </Batalla>
   <Batalla Enemigo_ID="32" Jugador_ID="3">
      <num_Turnos>10</num_Turnos>
      <num_Ayudantes>0</num_Ayudantes>
   </Batalla>
   <Batalla Enemigo_ID="2" Jugador_ID="4">
      <num_Turnos>9</num_Turnos>
      <num_Ayudantes>2</num_Ayudantes>
   </Batalla>
   <Batalla Enemigo_ID="10" Jugador_ID="5">
      <num_Turnos>3</num_Turnos>
      <num_Ayudantes>0</num_Ayudantes>
   </Batalla>
   <Batalla Enemigo_ID="66" Jugador_ID="6">
      <num_Turnos>9</num_Turnos>
      <num_Ayudantes>0</num_Ayudantes>
   </Batalla>
   <Batalla Enemigo_ID="41" Jugador_ID="7">
      <num_Turnos>4</num_Turnos>
      <num_Ayudantes>3</num_Ayudantes>
   </Batalla>
   <Batalla Enemigo_ID="23" Jugador_ID="8">
      <num_Turnos>2</num_Turnos>
      <num_Ayudantes>1</num_Ayudantes>
   </Batalla>
   <Batalla Enemigo_ID="4" Jugador_ID="9">
      <num_Turnos>6</num_Turnos>
      <num_Ayudantes>0</num_Ayudantes>
   </Batalla>
   <Batalla Enemigo_ID="44" Jugador_ID="10">
      <num_Turnos>4</num_Turnos>
      <num_Ayudantes>0</num_Ayudantes>
   </Batalla>
</Batallas>

=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/XML Defectuosos/batallas_defectuoso.xml
<?xml version="1.0" encoding="UTF-8"?>
<Batallas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="batallas.xsd">
    <Batalla Enemigo_ID="32" Jugador_ID="3">
      <!--El orden debe ser num_Turnos primero y despuÃ©s num_Ayudantes-->
      <num_Ayudantes>0</num_Ayudantes>
      <num_Turnos>10</num_Turnos>
      
   </Batalla>
   <!--Falta el atributo Jugador_ID cuando es required-->
   <Batalla Enemigo_ID="2">
      <num_Turnos>9</num_Turnos>
      <num_Ayudantes>2</num_Ayudantes>
   </Batalla>
   <Batalla Enemigo_ID="10" Jugador_ID="5">
      <!--num_Turnos es de tipo integer y tiene un string-->
      <num_Turnos>tres</num_Turnos>
      <num_Ayudantes>0</num_Ayudantes>
   </Batalla>
   <!--Falta el atributo Enemigo_ID cuando es required-->
   <!--El atributo Jugador_ID es de tipo positiveInteger, por lo que no puede ser 0-->
   <!--AdemÃ¡s, Jugador_ID tiene una restricciÃ³n por la que no puede ser menor de 1-->
   <Batalla Jugador_ID="0">
      <num_Turnos>9</num_Turnos>
      <num_Ayudantes>0</num_Ayudantes>
   </Batalla>
</Batallas>
