=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/Esquemas del XML (XSD)/enemigos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Enemigos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Enemigo" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Nombre" type="xs:string"/>
                            <xs:element name="Region" type="xs:string"/>
                            <xs:element name="Puntos_ataque" type="xs:integer"/>
                            <xs:element name="Puntos_defensa" type="xs:integer"/>
                            <xs:element name="Puntos_corazon" type="xs:integer"/>
                        </xs:sequence>
                        <xs:attribute name="Enemigo_ID" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:positiveInteger">
                                    <xs:minInclusive value="1"/>
                                </xs:restriction>
                            </xs:simpleType> 
                        </xs:attribute>
                        <xs:attribute name="Vuela" type="xs:boolean" use="required"/>
                        <xs:attribute name="Tiene_pincho" type="xs:boolean" use="required"/>
                        <xs:attribute name="Tiene_caparazon" type="xs:boolean" use="required"/>
                        <xs:attribute name="Es_Boss" type="xs:boolean" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/Tablas en XML/enemigos.xml
<?xml version="1.0" encoding="UTF-8"?>
<Enemigos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="enemigos.xsd">
   <Enemigo Enemigo_ID="1" Vuela="0" Tiene_pincho="0" Tiene_caparazon="0" Es_Boss="0">
      <Nombre>Goomba</Nombre>
      <Region>Diversos lugares</Region>
      <Puntos_ataque>1</Puntos_ataque>
      <Puntos_defensa>0</Puntos_defensa>
      <Puntos_corazon>2</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="2" Vuela="1" Tiene_pincho="0" Tiene_caparazon="0" Es_Boss="0">
      <Nombre>Paragoomba</Nombre>
      <Region>Diversos lugares</Region>
      <Puntos_ataque>1</Puntos_ataque>
      <Puntos_defensa>0</Puntos_defensa>
      <Puntos_corazon>2</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="3" Vuela="0" Tiene_pincho="1" Tiene_caparazon="0" Es_Boss="0">
      <Nombre>Goompincho</Nombre>
      <Region>Diversos lugares</Region>
      <Puntos_ataque>2</Puntos_ataque>
      <Puntos_defensa>0</Puntos_defensa>
      <Puntos_corazon>2</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="4" Vuela="0" Tiene_pincho="0" Tiene_caparazon="0" Es_Boss="0">
      <Nombre>Híper Goomba</Nombre>
      <Region>Camino Sombrío</Region>
      <Puntos_ataque>2</Puntos_ataque>
      <Puntos_defensa>0</Puntos_defensa>
      <Puntos_corazon>8</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="5" Vuela="1" Tiene_pincho="0" Tiene_caparazon="0" Es_Boss="0">
      <Nombre>Híper Paragoomba</Nombre>
      <Region>Camino Sombrío</Region>
      <Puntos_ataque>2</Puntos_ataque>
      <Puntos_defensa>0</Puntos_defensa>
      <Puntos_corazon>8</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="6" Vuela="0" Tiene_pincho="1" Tiene_caparazon="0" Es_Boss="0">
      <Nombre>Híper Goompincho</Nombre>
      <Region>Camino Sombrío</Region>
      <Puntos_ataque>3</Puntos_ataque>
      <Puntos_defensa>0</Puntos_defensa>
      <Puntos_corazon>8</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="7" Vuela="0" Tiene_pincho="0" Tiene_caparazon="0" Es_Boss="0">
      <Nombre>Gloomba</Nombre>
      <Region>Cien Mazmorras</Region>
      <Puntos_ataque>3</Puntos_ataque>
      <Puntos_defensa>0</Puntos_defensa>
      <Puntos_corazon>7</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="8" Vuela="1" Tiene_pincho="0" Tiene_caparazon="0" Es_Boss="0">
      <Nombre>Paragloomba</Nombre>
      <Region>Cien Mazmorras</Region>
      <Puntos_ataque>3</Puntos_ataque>
      <Puntos_defensa>0</Puntos_defensa>
      <Puntos_corazon>7</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="9" Vuela="0" Tiene_pincho="1" Tiene_caparazon="0" Es_Boss="0">
      <Nombre>Gloompincho</Nombre>
      <Region>Cien Mazmorras</Region>
      <Puntos_ataque>4</Puntos_ataque>
      <Puntos_defensa>0</Puntos_defensa>
      <Puntos_corazon>7</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="10" Vuela="0" Tiene_pincho="0" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Koopa Troopa</Nombre>
      <Region>Llanura Estelar</Region>
      <Puntos_ataque>2</Puntos_ataque>
      <Puntos_defensa>1</Puntos_defensa>
      <Puntos_corazon>4</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="11" Vuela="1" Tiene_pincho="0" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Paratroopa</Nombre>
      <Region>Castillo de Goombaba</Region>
      <Puntos_ataque>2</Puntos_ataque>
      <Puntos_defensa>1</Puntos_defensa>
      <Puntos_corazon>4</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="12" Vuela="0" Tiene_pincho="0" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Reservoir Troopa</Nombre>
      <Region>Ciudad Dojo</Region>
      <Puntos_ataque>2</Puntos_ataque>
      <Puntos_defensa>4</Puntos_defensa>
      <Puntos_corazon>4</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="13" Vuela="1" Tiene_pincho="0" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Reservoir Para</Nombre>
      <Region>Ciudad Dojo</Region>
      <Puntos_ataque>2</Puntos_ataque>
      <Puntos_defensa>1</Puntos_defensa>
      <Puntos_corazon>4</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="14" Vuela="0" Tiene_pincho="0" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Antitroopa</Nombre>
      <Region>Ciudad Dojo</Region>
      <Puntos_ataque>3</Puntos_ataque>
      <Puntos_defensa>1</Puntos_defensa>
      <Puntos_corazon>8</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="15" Vuela="1" Tiene_pincho="0" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Antipara</Nombre>
      <Region>Ciudad Dojo</Region>
      <Puntos_ataque>3</Puntos_ataque>
      <Puntos_defensa>1</Puntos_defensa>
      <Puntos_corazon>8</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="16" Vuela="0" Tiene_pincho="0" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Koopa Oscuro</Nombre>
      <Region>Cien Mazmorras</Region>
      <Puntos_ataque>4</Puntos_ataque>
      <Puntos_defensa>2</Puntos_defensa>
      <Puntos_corazon>8</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="17" Vuela="1" Tiene_pincho="0" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Paratroopa Oscuro</Nombre>
      <Region>Cien Mazmorras</Region>
      <Puntos_ataque>4</Puntos_ataque>
      <Puntos_defensa>2</Puntos_defensa>
      <Puntos_corazon>8</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="18" Vuela="0" Tiene_pincho="1" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Koopatrullero</Nombre>
      <Region>Subsuelo de Villa Viciosa</Region>
      <Puntos_ataque>4</Puntos_ataque>
      <Puntos_defensa>2</Puntos_defensa>
      <Puntos_corazon>6</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="19" Vuela="0" Tiene_pincho="1" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Koopatrullero Oscuro</Nombre>
      <Region>Ciudad Dojo</Region>
      <Puntos_ataque>5</Puntos_ataque>
      <Puntos_defensa>2</Puntos_defensa>
      <Puntos_corazon>25</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="20" Vuela="0" Tiene_pincho="0" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Koopa Esqueleto</Nombre>
      <Region>Castillo de Goombaba</Region>
      <Puntos_ataque>2</Puntos_ataque>
      <Puntos_defensa>1</Puntos_defensa>
      <Puntos_corazon>1</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="21" Vuela="0" Tiene_pincho="0" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Koopa Esqueleto Rojo</Nombre>
      <Region>Castillo de Goombaba</Region>
      <Puntos_ataque>3</Puntos_ataque>
      <Puntos_defensa>1</Puntos_defensa>
      <Puntos_corazon>5</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="22" Vuela="0" Tiene_pincho="0" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Huesitos</Nombre>
      <Region>Palacio de la Oscuridad</Region>
      <Puntos_ataque>5</Puntos_ataque>
      <Puntos_defensa>2</Puntos_defensa>
      <Puntos_corazon>8</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="23" Vuela="0" Tiene_pincho="0" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Koopa Esqueleto Negro</Nombre>
      <Region>Palacio de la Oscuridad</Region>
      <Puntos_ataque>5</Puntos_ataque>
      <Puntos_defensa>2</Puntos_defensa>
      <Puntos_corazon>20</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="24" Vuela="0" Tiene_pincho="0" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Hermano Martillo</Nombre>
      <Region>Ciudad Dojo</Region>
      <Puntos_ataque>4</Puntos_ataque>
      <Puntos_defensa>1</Puntos_defensa>
      <Puntos_corazon>7</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="25" Vuela="0" Tiene_pincho="0" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Hermano Boomerang</Nombre>
      <Region>Ciudad Dojo</Region>
      <Puntos_ataque>2</Puntos_ataque>
      <Puntos_defensa>1</Puntos_defensa>
      <Puntos_corazon>7</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="26" Vuela="0" Tiene_pincho="0" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Hermano Fuego</Nombre>
      <Region>Ciudad Dojo</Region>
      <Puntos_ataque>3</Puntos_ataque>
      <Puntos_defensa>1</Puntos_defensa>
      <Puntos_corazon>7</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="27" Vuela="1" Tiene_pincho="0" Tiene_caparazon="0" Es_Boss="0">
      <Nombre>Lakitu</Nombre>
      <Region>Ciudad Dojo</Region>
      <Puntos_ataque>2</Puntos_ataque>
      <Puntos_defensa>0</Puntos_defensa>
      <Puntos_corazon>5</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="28" Vuela="1" Tiene_pincho="0" Tiene_caparazon="0" Es_Boss="0">
      <Nombre>Lakitu Oscuro</Nombre>
      <Region>Cien Mazmorras</Region>
      <Puntos_ataque>5</Puntos_ataque>
      <Puntos_defensa>0</Puntos_defensa>
      <Puntos_corazon>13</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="29" Vuela="0" Tiene_pincho="1" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Pinchón</Nombre>
      <Region>Ciudad Dojo</Region>
      <Puntos_ataque>3</Puntos_ataque>
      <Puntos_defensa>3</Puntos_defensa>
      <Puntos_corazon>3</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="30" Vuela="0" Tiene_pincho="1" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Pinchón Celeste</Nombre>
      <Region>Cien Mazmorras</Region>
      <Puntos_ataque>6</Puntos_ataque>
      <Puntos_defensa>4</Puntos_defensa>
      <Puntos_corazon>6</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="31" Vuela="0" Tiene_pincho="0" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Buzzy Beetle</Nombre>
      <Region>Templo Lúgubre</Region>
      <Puntos_ataque>3</Puntos_ataque>
      <Puntos_defensa>4</Puntos_defensa>
      <Puntos_corazon>5</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="32" Vuela="0" Tiene_pincho="1" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Punzón</Nombre>
      <Region>Templo Lúgubre</Region>
      <Puntos_ataque>3</Puntos_ataque>
      <Puntos_defensa>4</Puntos_defensa>
      <Puntos_corazon>5</Puntos_corazon>
   </Enemigo>
   <Enemigo Enemigo_ID="33" Vuela="1" Tiene_pincho="0" Tiene_caparazon="1" Es_Boss="0">
      <Nombre>Parabuzzy</Nombre>
      <Region>Cueva de los Piratas</Region>
      <Puntos_ataque>3</Puntos_ataque>
      <Puntos_defensa>4</Puntos_defensa>
      <Puntos_corazon>5</Puntos_corazon>
   </Enemigo>
