=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/Esquemas del XML (XSD)/habilidad.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Habilidades">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Habilidad" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="Nombre"/>
                            <xs:element type="xs:nonNegativeInteger" name="Coste_PF"/>
                            <xs:element type="xs:nonNegativeInteger" name="Ind_atq"/>
                            <xs:element type="xs:nonNegativeInteger" name="Ind_def"/>
                            <xs:element type="xs:string" name="Descripcion"/>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="Personaje_nom"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
  </xs:element>
</xs:schema>

=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/XML Defectuosos/habilidad_defectuoso.xml
<?xml version="1.0" encoding="UTF-8"?>
<Habilidades xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="habilidad.xsd">
   <!-- Error numeros negativos -->
   <Habilidad Personaje_nom="Goomarina">
      <Nombre>Cabezazo</Nombre>
      <Coste_PF>-10000</Coste_PF>
      <Ind_atq>-4</Ind_atq>
      <Ind_def>-8990</Ind_def>
      <Descripcion>Ataca a un enemigo de un cabezazo.</Descripcion>
   </Habilidad>
   <!-- Error elementos desordenados -->
   <Habilidad Personaje_nom="Goomarina">
      <Descripcion>Ataca a un enemigo hasta fallar.</Descripcion>
      <Coste_PF>3</Coste_PF>
      <Ind_def>0</Ind_def>
      <Ind_atq>3</Ind_atq>
      <Nombre>Multicabezazo</Nombre>
   </Habilidad>
   <!-- Error mezcla de numeros y simbolos -->
   <Habilidad Personaje_nom="Goomarina">
      <Nombre>Beso de Ánimo</Nombre>
      <Coste_PF>4203+9485</Coste_PF>
      <Ind_atq>0384048+020''32'8498'2340934'034</Ind_atq>
      <Ind_def>0'0324985'93428'¿¡2034985330¡4</Ind_def>
      <Descripcion>Hace que Mario realice dos acciones en un turno.</Descripcion>
   </Habilidad>
   <!-- Error elementos vacios-->
   <Habilidad Personaje_nom="Koops">
      <Nombre></Nombre>
      <Coste_PF></Coste_PF>
      <Ind_atq></Ind_atq>
      <Ind_def></Ind_def>
      <Descripcion></Descripcion>
   </Habilidad>
   <!-- Error numeros decimales -->
   <Habilidad Personaje_nom="Koops">
      <Nombre>Súper Concha</Nombre>
      <Coste_PF>3.452</Coste_PF>
      <Ind_atq>2,434</Ind_atq>
      <Ind_def>0,2323</Ind_def>
      <Descripcion>Lanza la concha contra todos los enemigos.</Descripcion>
   </Habilidad>
   <!-- Error numeros seguidos-->
   <Habilidad Personaje_nom="Koops">
      <Nombre>Protegeconcha</Nombre>
      <Coste_PF>0000</Coste_PF>
      <Ind_atq>00100</Ind_atq>
      <Ind_def>00200</Ind_def>
      <Descripcion>Deja caer una concha que protege a Mario.</Descripcion>
   </Habilidad>
   <!-- Error  letras en vez de numeros-->
   <Habilidad Personaje_nom="Koops">
      <Nombre>Concha Furia</Nombre>
      <Coste_PF>pepe</Coste_PF>
      <Ind_atq>la rana pepe intenta reomper el sistema de ataque</Ind_atq>
      <Ind_def>El primo de pepe intenta eliminar tu defensa</Ind_def>
      <Descripcion>Ataca a todos los enemigos del suelo.</Descripcion>
   </Habilidad>
   <!-- Error personaje inexistente-->
   <Habilidad Personaje_nom="RanaPepe">
      <Nombre>Meme</Nombre>
      <Coste_PF>0</Coste_PF>
      <Ind_atq>4</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Te hace reir.</Descripcion>
   </Habilidad>
</Habilidades>

=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/Tablas en XML/habilidad.xml
<?xml version="1.0" encoding="UTF-8"?>
<Habilidades xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="habilidad.xsd">
   <Habilidad Personaje_nom="Goomarina">
      <Nombre>Cabezazo</Nombre>
      <Coste_PF>0</Coste_PF>
      <Ind_atq>4</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Ataca a un enemigo de un cabezazo.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Goomarina">
      <Nombre>Descripción</Nombre>
      <Coste_PF>0</Coste_PF>
      <Ind_atq>0</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Muestra la descripción del enemigo y sus PC.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Goomarina">
      <Nombre>Multicabezazo</Nombre>
      <Coste_PF>3</Coste_PF>
      <Ind_atq>3</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Ataca a un enemigo hasta fallar.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Goomarina">
      <Nombre>Beso de Ánimo</Nombre>
      <Coste_PF>4</Coste_PF>
      <Ind_atq>0</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Hace que Mario realice dos acciones en un turno.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Koops">
      <Nombre>Lanzaconcha</Nombre>
      <Coste_PF>0</Coste_PF>
      <Ind_atq>4</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Lanza la concha a un enemigo.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Koops">
      <Nombre>Súper Concha</Nombre>
      <Coste_PF>3</Coste_PF>
      <Ind_atq>2</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Lanza la concha contra todos los enemigos.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Koops">
      <Nombre>Protegeconcha</Nombre>
      <Coste_PF>4</Coste_PF>
      <Ind_atq>0</Ind_atq>
      <Ind_def>3</Ind_def>
      <Descripcion>Deja caer una concha que protege a Mario.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Koops">
      <Nombre>Concha Furia</Nombre>
      <Coste_PF>6</Coste_PF>
      <Ind_atq>4</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Ataca a todos los enemigos del suelo.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Claudia">
      <Nombre>Placaje</Nombre>
      <Coste_PF>0</Coste_PF>
      <Ind_atq>4</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Ataca a un enemigo aplastándolo con el cuerpo.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Claudia">
      <Nombre>Vendaval</Nombre>
      <Coste_PF>4</Coste_PF>
      <Ind_atq>2</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Levanta un vendaval y lanza a los enemigos por los aires.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Claudia">
      <Nombre>Achuchón</Nombre>
      <Coste_PF>3</Coste_PF>
      <Ind_atq>3</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Achucha al enemigo para drenar sus PC.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Claudia">
      <Nombre>Cortina Humo</Nombre>
      <Coste_PF>4</Coste_PF>
      <Ind_atq>0</Ind_atq>
      <Ind_def>2</Ind_def>
      <Descripcion>Hace que Mario esquive los ataques durante un rato.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Yoshi">
      <Nombre>Golpe Cadera</Nombre>
      <Coste_PF>0</Coste_PF>
      <Ind_atq>2</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Golpea al enemigo repetidamente.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Yoshi">
      <Nombre>Engullir</Nombre>
      <Coste_PF>4</Coste_PF>
      <Ind_atq>3</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Engulle a un enemigo para usarlo como arma arrojadiza.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Yoshi">
      <Nombre>Huevos Reductores</Nombre>
      <Coste_PF>3</Coste_PF>
      <Ind_atq>0</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Arroja huevos a los enemigos y los reduce de tamaño.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Yoshi">
      <Nombre>Estampida</Nombre>
      <Coste_PF>6</Coste_PF>
      <Ind_atq>2</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Ataca a los enemigos con una estampida de Yoshis.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Bibiana">
      <Nombre>Golpe Sombra</Nombre>
      <Coste_PF>0</Coste_PF>
      <Ind_atq>2</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Ataca a un enemigo con un puñetazo y le prende fuego.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Bibiana">
      <Nombre>Transparencia</Nombre>
      <Coste_PF>1</Coste_PF>
      <Ind_atq>0</Ind_atq>
      <Ind_def>3</Ind_def>
      <Descripcion>Esconde a Mario para evitar los ataques de los enemigos.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Bibiana">
      <Nombre>Llamarada</Nombre>
      <Coste_PF>6</Coste_PF>
      <Ind_atq>4</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Ataca a todos los enemigos con una llamarada.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Bibiana">
      <Nombre>Embelesamiento</Nombre>
      <Coste_PF>4</Coste_PF>
      <Ind_atq>0</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Confunde a los enemigos con un beso sensual.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Bombard">
      <Nombre>Bomba</Nombre>
      <Coste_PF>0</Coste_PF>
      <Ind_atq>4</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Explota atacando a un enemigo que esté en el suelo.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Bombard">
      <Nombre>Bomba Tiempo</Nombre>
      <Coste_PF>3</Coste_PF>
      <Ind_atq>3</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Arroja tres bombas que explotan un turno después.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Bombard">
      <Nombre>Mina</Nombre>
      <Coste_PF>4</Coste_PF>
      <Ind_atq>4</Ind_atq>
      <Ind_def>4</Ind_def>
      <Descripcion>Causa daño al enemigo que ataque a Bombard.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Bombard">
      <Nombre>Gran Explosión</Nombre>
      <Coste_PF>9</Coste_PF>
      <Ind_atq>4</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Explota atacando a todos los enemigos.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Lupina">
      <Nombre>Bofetada del Amor</Nombre>
      <Coste_PF>0</Coste_PF>
      <Ind_atq>4</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Ataca a un enemigo de una bofetada.</Descripcion>
   </Habilidad>
   <Habilidad Personaje_nom="Lupina">
      <Nombre>Beso Furtivo</Nombre>
      <Coste_PF>2</Coste_PF>
      <Ind_atq>0</Ind_atq>
      <Ind_def>0</Ind_def>
      <Descripcion>Roba los objetos y medallas que tengan los enemigos.</Descripcion>
   </Habilidad>
</Habilidades>
