=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/Esquemas del XML (XSD)/Items.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="items">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="item" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="descripcion" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/XML Defectuosos/items_defectuoso.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Elementos cambiados de orden -->
<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Items.xsd">
    <item>
        <descripcion>Recupera 5 PC.</descripcion>
        <nombre>Seta</nombre>
    </item>
    <item>
        <descripcion>Recupera 5 PF.</descripcion>
        <nombre>Gelatina</nombre>
    </item>
    <item>
        <descripcion>Recupera 15 PC.</descripcion>
        <nombre>Ultra Seta</nombre>
    </item>
    <item>
        <descripcion>Recupera 15 PF.</descripcion>
        <nombre>Grandimiel</nombre>
    </item>
    <item>
        <descripcion>Quita 3 PC a todos los enemigos.</descripcion>
        <nombre>Flor de fuego</nombre>
    </item>
    <item>
        <descripcion>Quita 2 PC a todos los enemigos y da vuelta a enemigos con caparazón</descripcion>
        <nombre>Bloque POW</nombre>
    </item>
    <item>
        <descripcion>Quita 4 PC a todos los enemigos.</descripcion>
        <nombre>Furia Trueno</nombre>
    </item>
    <item>
        <descripcion>Quita 6 PC a todos los enemigos.</descripcion>
        <nombre>Estrella Fugaz</nombre>
    </item>
    <item>
        <descripcion>Cura estados.</descripcion>
        <nombre>Tónico</nombre>
    </item>
    <item>
        <descripcion>Te cubre de ataques enemigos.</descripcion>
        <nombre>Espíritu</nombre>
    </item>
    <item>
        <descripcion>Marea a los enemigos.</descripcion>
        <nombre>Disco Mareo</nombre>
    </item>
    <item>
        <descripcion>Reduce el ataque de los enemigos.</descripcion>
        <nombre>Don Blandito</nombre>
    </item>
    <item>
        <descripcion>Te protege de ataques enemigos.</descripcion>
        <nombre>Concha Protectora</nombre>
    </item>
    <item>
        <descripcion>Esquiva ataques de enemigos</descripcion>
        <nombre>Capote</nombre>
    </item>
    <item>
        <descripcion>Quita PC a un enemigo y se lo da a tu personaje.</descripcion>
        <nombre>Chupa PC</nombre>
    </item>
    <item>
        <descripcion>Duerme a los enemigos.</descripcion>
        <nombre>Oveja Sueño</nombre>
    </item>
</items>

=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/Tablas en XML/Items.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Items.xsd">
    <item>
        <nombre>Seta</nombre>
        <descripcion>Recupera 5 PC.</descripcion>
    </item>
    <item>
        <nombre>Gelatina</nombre>
        <descripcion>Recupera 5 PF.</descripcion>
    </item>
    <item>
        <nombre>Ultra Seta</nombre>
        <descripcion>Recupera 15 PC.</descripcion>
    </item>
    <item>
        <nombre>Grandimiel</nombre>
        <descripcion>Recupera 15 PF.</descripcion>
    </item>
    <item>
        <nombre>Flor de fuego</nombre>
        <descripcion>Quita 3 PC a todos los enemigos.</descripcion>
    </item>
    <item>
        <nombre>Bloque POW</nombre>
        <descripcion>Quita 2 PC a todos los enemigos y da vuelta a enemigos con caparazón</descripcion>
    </item>
    <item>
        <nombre>Furia Trueno</nombre>
        <descripcion>Quita 4 PC a todos los enemigos.</descripcion>
    </item>
    <item>
        <nombre>Estrella Fugaz</nombre>
        <descripcion>Quita 6 PC a todos los enemigos.</descripcion>
    </item>
    <item>
        <nombre>Tónico</nombre>
        <descripcion>Cura estados.</descripcion>
    </item>
    <item>
        <nombre>Espíritu</nombre>
        <descripcion>Te cubre de ataques enemigos.</descripcion>
    </item>
    <item>
        <nombre>Disco Mareo</nombre>
        <descripcion>Marea a los enemigos.</descripcion>
    </item>
    <item>
        <nombre>Don Blandito</nombre>
        <descripcion>Reduce el ataque de los enemigos.</descripcion>
    </item>
    <item>
        <nombre>Concha Protectora</nombre>
        <descripcion>Te protege de ataques enemigos.</descripcion>
    </item>
    <item>
        <nombre>Capote</nombre>
        <descripcion>Esquiva ataques de enemigos</descripcion>
    </item>
    <item>
        <nombre>Chupa PC</nombre>
        <descripcion>Quita PC a un enemigo y se lo da a tu personaje.</descripcion>
    </item>
    <item>
        <nombre>Oveja Sueño</nombre>
        <descripcion>Duerme a los enemigos.</descripcion>
    </item>
</items>
