=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/Esquemas del XML (XSD)/jugador.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Jugadores">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Jugador" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="PC">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                      <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType> 
              </xs:element>
              <xs:element type="xs:integer" name="PE"/>
              <xs:element name="PF">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                      <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType> 
              </xs:element>
              <xs:element type="xs:integer" name="Monedas"/>
              <xs:element name="Estado">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                      <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType> 
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:integer" name="id"/>
            <xs:attribute type="xs:string" name="Personaje"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/Tablas en XML/jugador.xml
<?xml version="1.0" encoding="UTF-8"?>
<Jugadores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="jugador.xsd">
   <Jugador id="1" Personaje="Bombard">
      <PC>32</PC>
      <PE>0</PE>
      <PF>21</PF>
      <Monedas>104</Monedas>
      <Estado>4</Estado>
   </Jugador>
   <Jugador id="2" Personaje="Koops">
      <PC>34</PC>
      <PE>4</PE>
      <PF>30</PF>
      <Monedas>31</Monedas>
      <Estado>1</Estado>
   </Jugador>
   <Jugador id="3" Personaje="Bibiana">
      <PC>27</PC>
      <PE>4</PE>
      <PF>24</PF>
      <Monedas>48</Monedas>
      <Estado>1</Estado>
   </Jugador>
   <Jugador id="4" Personaje="Yoshi">
      <PC>18</PC>
      <PE>4</PE>
      <PF>26</PF>
      <Monedas>81</Monedas>
      <Estado>2</Estado>
   </Jugador>
   <Jugador id="5" Personaje="Koops">
      <PC>16</PC>
      <PE>0</PE>
      <PF>20</PF>
      <Monedas>72</Monedas>
      <Estado>5</Estado>
   </Jugador>
   <Jugador id="6" Personaje="Goomarina">
      <PC>19</PC>
      <PE>1</PE>
      <PF>30</PF>
      <Monedas>22</Monedas>
      <Estado>1</Estado>
   </Jugador>
   <Jugador id="7" Personaje="Lupina">
      <PC>8</PC>
      <PE>4</PE>
      <PF>20</PF>
      <Monedas>46</Monedas>
      <Estado>4</Estado>
   </Jugador>
   <Jugador id="8" Personaje="Claudia">
      <PC>2</PC>
      <PE>0</PE>
      <PF>22</PF>
      <Monedas>35</Monedas>
      <Estado>5</Estado>
   </Jugador>
   <Jugador id="9" Personaje="Bibiana">
      <PC>13</PC>
      <PE>1</PE>
      <PF>30</PF>
      <Monedas>5</Monedas>
      <Estado>2</Estado>
   </Jugador>
   <Jugador id="10" Personaje="Koops">
      <PC>12</PC>
      <PE>1</PE>
      <PF>23</PF>
      <Monedas>97</Monedas>
      <Estado>3</Estado>
   </Jugador>
</Jugadores>

=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/XML Defectuosos/jugador_defectuoso.xml
<?xml version="1.0" encoding="UTF-8"?>
<Jugadores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="jugador.xsd">
<!-- Los elementos del XML tienen un orden diferente al esperado -->
   <Jugador id="1" Personaje="Bombard">
      <Monedas>104</Monedas>
      <Estado>4</Estado>
      <PF>21</PF>
      <PE>0</PE>
      <PC>32</PC>
   </Jugador>
   <Jugador id="2" Personaje="Koops">
      <Monedas>31</Monedas>
      <Estado>1</Estado>
      <PF>30</PF>
      <PE>4</PE>
      <PC>34</PC>
   </Jugador>
   <Jugador id="3" Personaje="Bibiana">
      <Monedas>48</Monedas>
      <Estado>1</Estado>
      <PF>24</PF>
      <PE>4</PE>
      <PC>27</PC>
   </Jugador>
   <Jugador id="4" Personaje="Yoshi">
      <Monedas>81</Monedas>
      <Estado>2</Estado>
      <PF>26</PF>
      <PE>4</PE>
      <PC>18</PC>
   </Jugador>
   <Jugador id="5" Personaje="Koops">
      <Monedas>72</Monedas>
      <Estado>5</Estado>
      <PF>20</PF>
      <PE>0</PE>
      <PC>16</PC>
   </Jugador>
   <Jugador id="6" Personaje="Goomarina">
      <Monedas>22</Monedas>
      <Estado>1</Estado>
      <PF>30</PF>
      <PE>1</PE>
      <PC>19</PC>
   </Jugador>
   <Jugador id="7" Personaje="Lupina">
      <Monedas>46</Monedas>
      <Estado>4</Estado>
      <PF>20</PF>
      <PE>4</PE>
      <PC>8</PC>
   </Jugador>
   <Jugador id="8" Personaje="Claudia">
      <Monedas>35</Monedas>
      <Estado>5</Estado>
      <PF>22</PF>
      <PE>0</PE>
      <PC>2</PC>
   </Jugador>
   <Jugador id="9" Personaje="Bibiana">
      <Monedas>5</Monedas>
      <Estado>2</Estado>
      <PF>30</PF>
      <PE>1</PE>
      <PC>13</PC>
   </Jugador>
   <Jugador id="10" Personaje="Koops">
      <Monedas>97</Monedas>
      <Estado>3</Estado>
      <PF>23</PF>
      <PE>1</PE>
      <PC>12</PC>
   </Jugador>
</Jugadores>
