=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/Esquemas del XML (XSD)/jugador_items.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Jugadores_Items">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Jugador_Items" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="items_Nombre" type="xs:string"/>
                            <xs:element name="num_Items" type="maxObjetos"/>
                        </xs:sequence>
                        <xs:attribute name="Jugador_ID" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:positiveInteger">
                                    <xs:minInclusive value="1"/>
                                </xs:restriction>
                            </xs:simpleType> 
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="maxObjetos">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/XML Defectuosos/jugador_items_defectuoso.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Jugadores_Items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="jugador_items.xsd">
    <!--ID 0, no válido según la restricción y según el tipo (positiveInteger)-->
   <Jugador_Items Jugador_ID="0">
      <items_Nombre>Seta</items_Nombre>
      <num_Items>100</num_Items>
   </Jugador_Items>
   <Jugador_Items Jugador_ID="2">
      <items_Nombre>Espíritu</items_Nombre>
      <num_Items>59</num_Items>
   </Jugador_Items>
   <!--ID negativo, no válido según la restricción-->
   <Jugador_Items Jugador_ID="-3">
      <items_Nombre>Tónico</items_Nombre>
      <num_Items>81</num_Items>
   </Jugador_Items>
   <Jugador_Items Jugador_ID="4">
      <items_Nombre>Concha Protectora</items_Nombre>
      <num_Items>99</num_Items>
   </Jugador_Items>
   <!--No aparece el ID-->
   <Jugador_Items>
      <items_Nombre>Chupa PC</items_Nombre>
      <num_Items>87</num_Items>
   </Jugador_Items>
   <Jugador_Items Jugador_ID="6">
      <items_Nombre>Furia trueno</items_Nombre>
      <!--Número de items igual que el límite superior establecido-->
      <num_Items>100</num_Items>
   </Jugador_Items>
   <Jugador_Items Jugador_ID="7">
      <items_Nombre>Flor de fuego</items_Nombre>
      <!--Número de items que supera el límite superior establecido-->
      <num_Items>101</num_Items>
   </Jugador_Items>
   <Jugador_Items Jugador_ID="8">
      <items_Nombre>Gelatina</items_Nombre>
      <num_Items>75</num_Items>
   </Jugador_Items>
   <Jugador_Items Jugador_ID="9">
      <items_Nombre>Oveja Sueño</items_Nombre>
      <!--Número de items que está por debajo del límite inferior establecido-->
      <num_Items>0</num_Items>
   </Jugador_Items>
   <Jugador_Items Jugador_ID="10">
      <items_Nombre>Capote</items_Nombre>
      <num_Items>55</num_Items>
   </Jugador_Items>
</Jugadores_Items>
