=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/Esquemas del XML (XSD)/lugar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Lugares">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Lugar" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="Nombre"/>
              <xs:element name="Npc">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                      <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType> 
              </xs:element>
              <xs:element type="xs:integer" name="Enemigos"/> 
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/XML Defectuosos/lugar_defectuoso.xml
<?xml version="1.0" encoding="UTF-8"?>
<Lugares xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="lugar.xsd">
<!-- Los elementos del XML tienen un orden diferente al esperado -->
   <Lugar>
       <Npc>15</Npc>
       <Nombre>Villa Viciosa</Nombre>
      <Enemigos>14</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>13</Npc>
       <Nombre>Subsuelo de Villa Viciosa</Nombre>
      <Enemigos>8</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>14</Npc>
       <Nombre>Llanura Estelar</Nombre>
      <Enemigos>9</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>7</Npc>
       <Nombre>Villa Verde</Nombre>
      <Enemigos>0</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>8</Npc>
       <Nombre>Fortaleza de Piedra</Nombre>
      <Enemigos>13</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>12</Npc>
       <Nombre>Castillo de Goombaba</Nombre>
      <Enemigos>17</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>17</Npc>
       <Nombre>Bosque Maravilloso</Nombre>
      <Enemigos>19</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>12</Npc>
       <Nombre>Gran Árbol</Nombre>
      <Enemigos>8</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>7</Npc>
       <Nombre>Casa de Claudia</Nombre>
      <Enemigos>0</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>9</Npc>
       <Nombre>Ciudad Dojo</Nombre>
      <Enemigos>16</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>18</Npc>
       <Nombre>Villa Sombría</Nombre>
      <Enemigos>20</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>16</Npc>
       <Nombre>Camino Sombrío</Nombre>
      <Enemigos>18</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>12</Npc>
       <Nombre>Templo Lúgubre</Nombre>
      <Enemigos>9</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>11</Npc>
       <Nombre>Isla Trópico</Nombre>
      <Enemigos>5</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>11</Npc>
       <Nombre>Cueva de los Piratas</Nombre>
      <Enemigos>20</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>9</Npc>
       <Nombre>Estación de Riverside</Nombre>
      <Enemigos>16</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>18</Npc>
       <Nombre>Villa Preciosa</Nombre>
      <Enemigos>0</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>12</Npc>
       <Nombre>Bomburgo</Nombre>
      <Enemigos>14</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>7</Npc>
       <Nombre>La Luna</Nombre>
      <Enemigos>6</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>8</Npc>
       <Nombre>Palacio de la Oscuridad</Nombre>
      <Enemigos>11</Enemigos>
   </Lugar>
   <Lugar>
       <Npc>15</Npc>
       <Nombre>Cien Mazmorras</Nombre>
      <Enemigos>7</Enemigos>
   </Lugar>
</Lugares>

=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/Tablas en XML/lugar.xml
<?xml version="1.0" encoding="UTF-8"?>
<Lugares xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="lugar.xsd">
   <Lugar>
      <Nombre>Villa Viciosa</Nombre>
      <Npc>15</Npc>
      <Enemigos>14</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>Subsuelo de Villa Viciosa</Nombre>
      <Npc>13</Npc>
      <Enemigos>8</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>Llanura Estelar</Nombre>
      <Npc>14</Npc>
      <Enemigos>9</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>Villa Verde</Nombre>
      <Npc>7</Npc>
      <Enemigos>0</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>Fortaleza de Piedra</Nombre>
      <Npc>8</Npc>
      <Enemigos>13</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>Castillo de Goombaba</Nombre>
      <Npc>12</Npc>
      <Enemigos>17</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>Bosque Maravilloso</Nombre>
      <Npc>17</Npc>
      <Enemigos>19</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>Gran Árbol</Nombre>
      <Npc>12</Npc>
      <Enemigos>8</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>Casa de Claudia</Nombre>
      <Npc>7</Npc>
      <Enemigos>0</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>Ciudad Dojo</Nombre>
      <Npc>9</Npc>
      <Enemigos>16</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>Villa Sombría</Nombre>
      <Npc>18</Npc>
      <Enemigos>20</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>Camino Sombrío</Nombre>
      <Npc>16</Npc>
      <Enemigos>18</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>Templo Lúgubre</Nombre>
      <Npc>12</Npc>
      <Enemigos>9</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>Isla Trópico</Nombre>
      <Npc>11</Npc>
      <Enemigos>5</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>Cueva de los Piratas</Nombre>
      <Npc>11</Npc>
      <Enemigos>20</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>Estación de Riverside</Nombre>
      <Npc>9</Npc>
      <Enemigos>16</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>Villa Preciosa</Nombre>
      <Npc>18</Npc>
      <Enemigos>0</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>Bomburgo</Nombre>
      <Npc>12</Npc>
      <Enemigos>14</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>La Luna</Nombre>
      <Npc>7</Npc>
      <Enemigos>6</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>Palacio de la Oscuridad</Nombre>
      <Npc>8</Npc>
      <Enemigos>11</Enemigos>
   </Lugar>
   <Lugar>
      <Nombre>Cien Mazmorras</Nombre>
      <Npc>15</Npc>
      <Enemigos>7</Enemigos>
   </Lugar>
</Lugares>
