=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/Esquemas del XML (XSD)/partida.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Partidas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Partida" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Nombre" type="xs:string"/>
                            <xs:element name="Horas" type="xs:positiveInteger"/>
                        </xs:sequence>
                        <xs:attribute name="User_id" type="xs:positiveInteger"/>
                        <xs:attribute name="Jug_id" type="xs:positiveInteger"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
  </xs:element>
</xs:schema>

=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/Tablas en XML/partida.xml
<?xml version="1.0" encoding="UTF-8"?>
<Partidas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="partida.xsd">
   <Partida User_id="1" Jug_id="1">
      <Nombre>Alberto</Nombre>
      <Horas>19</Horas>
   </Partida>
   <Partida User_id="2" Jug_id="2">
      <Nombre>Alejandro</Nombre>
      <Horas>27</Horas>
   </Partida>
   <Partida User_id="3" Jug_id="3">
      <Nombre>Blanca</Nombre>
      <Horas>27</Horas>
   </Partida>
   <Partida User_id="4" Jug_id="4">
      <Nombre>Carlota</Nombre>
      <Horas>40</Horas>
   </Partida>
   <Partida User_id="5" Jug_id="5">
      <Nombre>Emilio</Nombre>
      <Horas>49</Horas>
   </Partida>
   <Partida User_id="6" Jug_id="6">
      <Nombre>Héctor</Nombre>
      <Horas>24</Horas>
   </Partida>
   <Partida User_id="7" Jug_id="7">
      <Nombre>Irene</Nombre>
      <Horas>17</Horas>
   </Partida>
   <Partida User_id="8" Jug_id="8">
      <Nombre>Luis</Nombre>
      <Horas>17</Horas>
   </Partida>
   <Partida User_id="9" Jug_id="9">
      <Nombre>Sandro</Nombre>
      <Horas>46</Horas>
   </Partida>
   <Partida User_id="10" Jug_id="10">
      <Nombre>Verónica</Nombre>
      <Horas>28</Horas>
   </Partida>
</Partidas>

=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/XML Defectuosos/partida_defectuoso.xml
<?xml version="1.0" encoding="UTF-8"?>
<Partidas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="partida.xsd">
   <!-- Error elementos desordenados-->
   <Partida User_id="1" Jug_id="1">
      <Horas>19</Horas>
      <Nombre>Alberto</Nombre>
   </Partida>
   <!-- Error ids negativos-->
   <Partida User_id="-2" Jug_id="-2">
      <Nombre>Alejandro</Nombre>
      <Horas>27</Horas>
   </Partida>
   <!-- Error ids con letras-->
   <Partida User_id="rana" Jug_id="pepe">
      <Nombre>Blanca</Nombre>
      <Horas>27</Horas>
   </Partida>
   <!-- Error etiquetas vacias-->
   <Partida User_id="5" Jug_id="5">
      <Nombre></Nombre>
      <Horas></Horas>
   </Partida>
   <!-- Error ids vacios -->
   <Partida User_id="" Jug_id="">
      <Nombre>SinId</Nombre>
      <Horas>24</Horas>
   </Partida>
   <!-- Error horas negativas -->
   <Partida User_id="7" Jug_id="7">
      <Nombre>Irene</Nombre>
      <Horas>-17</Horas>
   </Partida>
   <!-- Error ids con letras-->
   <Partida User_id="asdf" Jug_id="asdf">
      <Nombre>Luis</Nombre>
      <Horas>17</Horas>
   </Partida>
   <!-- Error ids negativos-->
   <Partida User_id="-1" Jug_id="-1">
      <Nombre>Sandro</Nombre>
      <Horas>46</Horas>
   </Partida>
</Partidas>
