=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/Esquemas del XML (XSD)/usuario.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?> 
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Usuarios">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Usuario" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Nombre" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:positiveInteger">
                                    <xs:minInclusive value="1"/>
                                </xs:restriction>
                            </xs:simpleType> 
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Luangoma/GDDV3B-GestionDeDatos/Practica Grupal 2 - XML y XSD/XML Defectuosos/usuario_defectuoso.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Usuarios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="usuario.xsd">
<!--id 0, por debajo del valor mínimo indicado en la restricción, tampoco está aceptado
por el tipo positiveInteger-->
   <Usuario id="0">
      <Nombre>Alberto</Nombre>
   </Usuario>
   <Usuario id="2">
      <Nombre>Alejandro</Nombre>
   </Usuario>
   <!--No aparece id cuando es obligatorio-->
   <Usuario>
      <Nombre>Blanca</Nombre>
   </Usuario>
   <Usuario id="4">
      <Nombre>Carlota</Nombre>
   </Usuario>
   <Usuario id="5">
      <Nombre>Emilio</Nombre>
   </Usuario>
   <Usuario id="6">
      <Nombre>Héctor</Nombre>
   </Usuario>
   <Usuario id="7">
      <Nombre>Irene</Nombre>
   </Usuario>
   <!--El id es negativo, por debajo del valor mínimo indicado en la restricción, tampoco está aceptado
   por el tipo positiveInteger-->
   <Usuario id="-25">
      <Nombre>Luis</Nombre>
   </Usuario>
   <Usuario id="9">
      <Nombre>Sandro</Nombre>
   </Usuario>
   <Usuario id="10">
      <Nombre>Verónica</Nombre>
   </Usuario>
</Usuarios>
